apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: database-app
  name: database-app
spec:
  containers:
  - image: mysql:latest
    name: database-app
    resources: {}
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: rootpassword
    - name: MYSQL_DATABASE
      value: wordpressdb
    - name: MYSQL_USER
      value: wpuser
    - name: MYSQL_PASSWORD
      value: wppassword
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
