apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod3
  name: pod3
spec:
  containers:
  - image: nginx:latest
    name: pod3
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  nodeSelector:
    mysize: small
status: {}
