apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: pod2
  name: pod2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pod2
    spec:
      containers:
      - image: busybox:1.27.2
        name: busybox
        command: ["sleep", "3600"]
        volumeMounts:
          - name: pod-volume
            mountPath: /busybox
        
      volumes:
        - name: pod-volume
          emptyDir: {}
status: {}
