apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod2
  name: pod3
spec:
  containers:
  - image: nginx:latest
    name: pod2
  tolerations:
    - effect: NoSchedule
      operator: Equal
      key: mysize
      value: small
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
