apiVersion: v1
data:
  secret-file.sh: ZWNobyAiU3RvcmUgQWxsIHRoZSBJbmZvIgoKZWNobyAiREJfVVNFUk5BTUU9YWRtaW4iCmVjaG8gIkRCX1BBU1NXT1JEPXBhc3N3b3JkIgplY2hvICJEQl9EQVRBQkFTRT1jdXN0b21lcl9kYiIKZWNobyAiREJfUE9SVD0zMzA2IgplY2hvICJEQl9IT1NUPWxvY2FsaG9zdCI=
kind: Secret
metadata:
  creationTimestamp: "2025-09-26T08:33:17Z"
  name: secretfromfile
  namespace: default
  resourceVersion: "43376"
  uid: e2342700-d547-4881-be2c-1ac34ab55a64
type: Opaque
